//! Shared vocabulary: the typed event stream a provider Session emits.
//!
//! SessionEvent grows as a superset, append-only — provider concepts keep
//! typed payloads; nothing is flattened to a lowest common denominator.

/// One structured event from a provider Session.
#[derive(Debug, Clone, PartialEq)]
pub enum SessionEvent {
    /// Attributed execution and discovery. Child facts must enter Activity
    /// before any Main transcript, usage, queue, or resume bookkeeping.
    Activity(crate::activity::ActivityEvent),
    /// The provider session is live. `session_id` is the provider-native id
    /// later used for resume.
    Init {
        session_id: String,
        model: String,
    },
    /// The provider rerouted the live Session to a different effective model.
    /// The Session identity and the Thread's chosen model do not change.
    ModelChanged {
        model: String,
    },
    /// The provider replaced its native conversation while this Session stays live.
    ConversationReset {
        session_id: String,
    },
    /// Assistant text streamed in.
    TextDelta {
        text: String,
    },
    /// Extended thinking streamed in (Claude).
    ThinkingDelta {
        text: String,
    },
    /// A tool call the provider has settled and is about to run. `input` is
    /// the tool's own schema, so it stays a `Value`: inventing a Ferrite type
    /// per tool would be a guess that goes stale on the vendor's next release.
    ToolStarted {
        id: String,
        name: String,
        input: serde_json::Value,
    },
    /// A tool call finished. `output` is exactly what the provider fed back to
    /// the model — text as text, anything else as its compact JSON.
    ///
    /// Claude also reports a *structured* result alongside it (a stdout/stderr
    /// pair for Bash, a patch for an edit). Nothing renders that yet, so it is
    /// not modelled here; the committed fixtures carry it under
    /// `tool_use_result` for whoever builds diff cards.
    ToolCompleted {
        id: String,
        output: String,
        is_error: bool,
        /// The provider's own structured result, where Ferrite models the
        /// shape — a diff card cannot be drawn from `output`, which is prose
        /// written for the model.
        result: ToolResult,
    },
    /// Operator input is requested. `Decision::blocks_execution` distinguishes
    /// tool approvals from questions delivered while execution continues. Answer
    /// with the provider's respond-to-Decision call, quoting the Decision's `id`.
    DecisionRequested {
        decision: Decision,
    },
    /// One native reasoning-summary section. Identity survives deltas and
    /// authoritative snapshots, so a completion can correct an earlier part.
    ReasoningSummaryPart {
        item_id: String,
        summary_index: u64,
        text: String,
        snapshot: bool,
    },
    /// Native provider activity; never generated by a second agent/model.
    Progress {
        event: crate::progress::ProgressEvent,
    },
    /// Incremental output for an existing tool, before it completes.
    ToolOutputDelta {
        id: String,
        text: String,
    },
    FileChanges {
        id: String,
        edits: Vec<FileEdit>,
    },
    TurnDiff {
        turn_id: String,
        diff: String,
    },
    /// The provider closed a content item. The next item must not merge
    /// with its predecessor merely because no tool separated their text.
    ContentBoundary,
    /// A turn finished.
    TurnEnded {
        outcome: TurnOutcome,
        cost_usd: Option<f64>,
    },
    /// The provider's current Main runtime state. This is a snapshot, never
    /// evidence that a turn finished.
    RunState {
        state: RunState,
    },
    /// A slice of a reasoning summary streamed in (Codex). Not a thinking
    /// delta: Codex never streams raw chain-of-thought over app-server —
    /// these are the model-authored summaries of hidden reasoning, arriving
    /// part by part.
    ReasoningSummaryDelta {
        text: String,
        /// Which summary part this delta extends; a new index starts a new
        /// part, so a Pane can break paragraphs where the provider did.
        summary_index: u64,
    },
    /// Provider-reported context occupancy and output accounting. Codex's
    /// output counters accumulate across the Session; Claude reports them
    /// per message/turn. Neither is the current context size.
    TokenUsage {
        /// The latest active context size, including input and output.
        total_tokens: u64,
        input_tokens: u64,
        cached_input_tokens: u64,
        output_tokens: u64,
        reasoning_output_tokens: u64,
        /// The model's context window, when the provider states it.
        context_window: Option<u64>,
    },
    /// Provider-reported occupancy without accounting counters.
    ContextUsage {
        total_tokens: u64,
        context_window: Option<u64>,
    },
    /// Native accounting counters, with the scope the provider assigned them.
    UsageDetails {
        details: UsageDetails,
    },
    /// Provider-reported subscription usage. Windows are named by duration,
    /// rather than by the provider's primary/secondary ordering, because that
    /// ordering is not stable across plans.
    RateLimits {
        five_hour: Option<RateLimitWindow>,
        weekly: Option<RateLimitWindow>,
    },
    /// The Session's own command menu, announced at Session start — what the
    /// Composer's `/` popover lists (#23). Claude lifts it from the initialize
    /// handshake's `commands[]`; Codex answers a `skills/list` request. Session
    /// state like a Decision, not durable history: a replacement Session
    /// announces its own.
    Commands {
        commands: Vec<SessionCommand>,
    },
    /// The permission mode the Session started in, in the provider's own
    /// word (`"acceptEdits"`, `"bypassPermissions"`, …) — the Composer's
    /// meta-row mode chip (#23). Claude lifts it from the same initialize
    /// handshake; display-only, and Session state like the menu above.
    PermissionMode {
        mode: String,
    },
    /// The models this install offers, each with the name the provider's
    /// own menu shows — the model picker's rows (#25). Claude lifts the
    /// list from the same initialize handshake; Codex asks `model/list`
    /// once its thread is up. Until either speaks the picker falls back
    /// to the catalog in `providers::models`. Session state exactly like
    /// the command menu: gone with the Session.
    Models {
        models: Vec<ModelInfo>,
    },
    /// A native context refresh with provider-neutral detail.
    ContextDetails {
        details: ContextDetails,
    },
    /// Current MCP server state for this Session.
    McpServers {
        servers: Vec<McpServer>,
    },
    /// Live authorization link; never persisted or opened automatically.
    McpAuthorization {
        server: String,
        url: Option<String>,
    },
    /// The session process exited; no further events will arrive.
    Closed {
        reason: String,
    },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum UsageScope {
    Message,
    Turn,
    Session,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct UsageDetails {
    pub scope: UsageScope,
    pub input_tokens: u64,
    pub cached_input_tokens: u64,
    pub output_tokens: u64,
    pub reasoning_output_tokens: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ControlKind {
    RefreshContext,
    RefreshMcp,
    ReconnectMcp,
    LoginMcp,
    ReloadMcp,
    StopTask,
    BackgroundTasks,
    SetPermissionMode,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SessionControl {
    RefreshContext,
    RefreshMcp,
    ReconnectMcp { server: String },
    LoginMcp { server: String },
    ReloadMcp,
    StopTask { id: String },
    BackgroundTasks,
    SetPermissionMode { mode: String },
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ContextDetails {
    pub usable_window: Option<u64>,
    pub auto_compact_threshold: Option<u64>,
    pub is_auto_compact_enabled: Option<bool>,
    pub categories: Vec<ContextCategory>,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ContextCategory {
    pub name: String,
    pub tokens: u64,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct McpServer {
    pub name: String,
    pub status: McpStatus,
    pub error: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum McpStatus {
    Connected,
    Connecting,
    NeedsAuth,
    Failed,
    Disabled,
    Unknown,
}

/// One rolling subscription limit, normalized to a fraction for the UI while
/// retaining the provider's reset instant for detail surfaces.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct RateLimitWindow {
    pub used_fraction: f32,
    pub resets_at: Option<u64>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RunState {
    Running,
    RequiresAction,
    Idle,
}

/// One model a provider offers: the value its CLI accepts, and the name a
/// person reads. The value is what goes on the wire (`--model sonnet`,
/// `"model": "gpt-5.6"`); the display is what every chip and row shows.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct ModelInfo {
    /// What the provider accepts as the model choice: an alias (`sonnet`,
    /// `opus[1m]`) or a full id (`claude-fable-5-1`, `gpt-5.6`).
    pub value: String,
    /// The human name — `Fable 5.1`, `Opus (1M context)`, `GPT-5.6 Sol`.
    pub display: String,
    /// One line of detail the provider's menu shows beside the name, or
    /// empty.
    pub detail: String,
    /// The full id the value resolves to, when the provider says — how the
    /// model a Session's Init names is matched back to its row.
    pub resolved: Option<String>,
    /// The effort levels this model accepts, in the provider's own words
    /// and order (`low` … `max`, Codex adds `ultra` on some). Empty means
    /// the model takes no effort setting — Haiku, for one — and the picker
    /// offers none.
    pub efforts: Vec<String>,
    /// The effort the provider applies when none is asked for, when it
    /// says (Codex does; Claude does not).
    pub default_effort: Option<String>,
}

impl ModelInfo {
    /// A model known only by its value: the display is groomed from it,
    /// and nothing is known about its efforts.
    pub fn bare(value: impl Into<String>) -> Self {
        let value = value.into();
        Self {
            display: crate::providers::models::display_name(&value),
            detail: String::new(),
            resolved: None,
            efforts: Vec::new(),
            default_effort: None,
            value,
        }
    }

    /// Whether `model` — an Init's full id or a chosen value — is this row.
    pub fn is(&self, model: &str) -> bool {
        self.value == model || self.resolved.as_deref() == Some(model)
    }
}

impl From<&str> for ModelInfo {
    fn from(value: &str) -> Self {
        Self::bare(value)
    }
}

impl PartialEq<str> for ModelInfo {
    fn eq(&self, other: &str) -> bool {
        self.value == other
    }
}

/// One entry of a Session's command menu, in the provider's own words.
#[derive(Debug, Clone, PartialEq)]
pub struct SessionCommand {
    /// What the operator types after `/`.
    pub name: String,
    pub description: String,
    /// Codex only: the SKILL.md a typed `{"type":"skill"}` input item must
    /// carry. Claude commands have none — the CLI dispatches on the text.
    pub path: Option<String>,
}

/// The structured half of a tool result. Every shape here was read off a
/// recorded capture; anything else stays `Opaque` rather than being guessed at.
#[derive(Debug, Clone, Default, PartialEq)]
pub enum ToolResult {
    /// No structured payload, or one Ferrite does not model.
    #[default]
    Opaque,
    /// A command ran and wrote to the usual two streams.
    Command {
        stdout: String,
        stderr: String,
        exit_code: Option<i64>,
        duration_ms: Option<u64>,
    },
    /// A provider payload Ferrite preserves without claiming a narrower shape.
    Structured {
        value: serde_json::Value,
        duration_ms: Option<u64>,
    },
    /// A file was written. `hunks` is empty when the file was created, which
    /// has nothing to diff against.
    FileEdit { path: String, hunks: Vec<Hunk> },
    /// One call changed several files.
    FileEdits { edits: Vec<FileEdit> },
}

impl ToolResult {
    /// Native execution time when the provider supplied one.
    pub fn duration_ms(&self) -> Option<u64> {
        match self {
            Self::Command { duration_ms, .. } | Self::Structured { duration_ms, .. } => {
                *duration_ms
            }
            _ => None,
        }
    }
}

/// One file in a multi-file tool result.
#[derive(Debug, Clone, PartialEq)]
pub struct FileEdit {
    pub path: String,
    pub hunks: Vec<Hunk>,
}

/// One changed region of a file, in the provider's own unified-diff form.
#[derive(Debug, Clone, PartialEq)]
pub struct Hunk {
    pub old_start: u32,
    pub old_lines: u32,
    pub new_start: u32,
    pub new_lines: u32,
    /// Each line keeps its marker: ' ' context, '-' removed, '+' added.
    pub lines: Vec<String>,
}

/// Provider-normalized delivery, independent of tool names and input schemas.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum DecisionDelivery {
    #[default]
    Blocking,
    Async,
}

/// The one provider-neutral interaction a Decision asks the operator to make.
#[derive(Debug, Clone, Default, PartialEq)]
pub enum DecisionKind {
    /// Permit or reject an action without collecting extra input.
    #[default]
    Approval,
    /// A sequence of choices and optional free-text answers.
    Questions(Vec<crate::questions::Question>),
    /// A typed, flat set of MCP fields.
    Form { fields: Vec<FormField> },
    /// A URL the operator may complete outside Ferrite. Ferrite never opens it.
    External { url: String },
    /// A native request Ferrite can safely dismiss but cannot render yet.
    Unsupported { reason: String },
}

/// Provider-normalized controls for an approval card.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct DecisionPolicy {
    pub allow: bool,
    pub deny: bool,
    pub prefer_deny: bool,
    pub interaction_required: bool,
}

/// One provider-normalized label paired with its opaque reply token.
#[derive(Debug, Clone, PartialEq)]
pub struct DecisionChoice {
    pub label: String,
    pub value: serde_json::Value,
    pub standing: bool,
}

impl Default for DecisionPolicy {
    fn default() -> Self {
        Self {
            allow: true,
            deny: true,
            prefer_deny: false,
            interaction_required: false,
        }
    }
}

/// One provider-neutral field in an MCP elicitation form.
#[derive(Debug, Clone, PartialEq)]
pub struct FormField {
    pub id: String,
    pub label: String,
    pub description: String,
    pub required: bool,
    pub kind: FormFieldKind,
}

/// One rendered label and the wire value it represents.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FormChoice {
    pub value: String,
    pub label: String,
}

/// A provider-native permission mode offered by the shared picker.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PermissionModeChoice {
    pub value: String,
    pub label: String,
}

/// Constraints and defaults for the MCP flat primitive subset.
#[derive(Debug, Clone, PartialEq)]
pub enum FormFieldKind {
    String {
        min_length: Option<usize>,
        max_length: Option<usize>,
        default: Option<String>,
    },
    Number {
        minimum: Option<f64>,
        maximum: Option<f64>,
        default: Option<f64>,
    },
    Integer {
        minimum: Option<i64>,
        maximum: Option<i64>,
        default: Option<i64>,
    },
    Boolean {
        default: Option<bool>,
    },
    Enum {
        options: Vec<FormChoice>,
        multi_select: bool,
        min_items: Option<usize>,
        max_items: Option<usize>,
        default: Option<serde_json::Value>,
    },
}

impl FormField {
    /// Validate one operator-provided JSON value before its adapter writes an
    /// MCP response. Schema decoding is deliberately outside this module.
    pub fn validate(&self, value: &serde_json::Value) -> Result<(), String> {
        match &self.kind {
            FormFieldKind::String {
                min_length,
                max_length,
                ..
            } => {
                let Some(text) = value.as_str() else {
                    return Err(format!("{} must be a string", self.label));
                };
                let length = text.chars().count();
                if min_length.is_some_and(|min| length < min)
                    || max_length.is_some_and(|max| length > max)
                {
                    return Err(format!("{} is outside its allowed length", self.label));
                }
            }
            FormFieldKind::Number {
                minimum, maximum, ..
            } => {
                let Some(number) = value.as_f64() else {
                    return Err(format!("{} must be a number", self.label));
                };
                if minimum.is_some_and(|min| number < min)
                    || maximum.is_some_and(|max| number > max)
                {
                    return Err(format!("{} is outside its allowed range", self.label));
                }
            }
            FormFieldKind::Integer {
                minimum, maximum, ..
            } => {
                let Some(number) = value.as_i64() else {
                    return Err(format!("{} must be an integer", self.label));
                };
                if minimum.is_some_and(|min| number < min)
                    || maximum.is_some_and(|max| number > max)
                {
                    return Err(format!("{} is outside its allowed range", self.label));
                }
            }
            FormFieldKind::Boolean { .. } if !value.is_boolean() => {
                return Err(format!("{} must be true or false", self.label));
            }
            FormFieldKind::Boolean { .. } => {}
            FormFieldKind::Enum {
                options,
                multi_select,
                min_items,
                max_items,
                ..
            } => {
                let values: Vec<&str> = if *multi_select {
                    value
                        .as_array()
                        .ok_or_else(|| format!("{} must be a list", self.label))?
                        .iter()
                        .map(|value| {
                            value
                                .as_str()
                                .ok_or_else(|| format!("{} has an invalid choice", self.label))
                        })
                        .collect::<Result<_, _>>()?
                } else {
                    vec![value
                        .as_str()
                        .ok_or_else(|| format!("{} has an invalid choice", self.label))?]
                };
                if values
                    .iter()
                    .any(|value| !options.iter().any(|option| option.value == *value))
                {
                    return Err(format!("{} has an unavailable choice", self.label));
                }
                if *multi_select && values.iter().enumerate().any(|(i, value)| values[..i].contains(value)) {
                    return Err(format!("{} contains duplicate choices", self.label));
                }
                if *multi_select
                    && (min_items.is_some_and(|min| values.len() < min)
                        || max_items.is_some_and(|max| values.len() > max))
                {
                    return Err(format!("{} has an invalid number of choices", self.label));
                }
            }
        }
        Ok(())
    }
}

/// Validate the values for a normalized Form before encoding a provider reply.
pub fn validate_form(fields: &[FormField], values: &serde_json::Value) -> Result<(), String> {
    let values = values
        .as_object()
        .ok_or_else(|| "form values must be an object".to_string())?;
    for field in fields {
        match values.get(&field.id) {
            Some(value) if !value.is_null() => field.validate(value)?,
            _ if field.required => return Err(format!("{} is required", field.label)),
            _ => {}
        }
    }
    if values
        .keys()
        .any(|id| !fields.iter().any(|field| field.id == *id))
    {
        return Err("form contains an unsupported field".into());
    }
    Ok(())
}

/// A provider request for operator input.
#[derive(Debug, Clone, PartialEq)]
pub struct Decision {
    pub delivery: DecisionDelivery,
    pub kind: DecisionKind,
    pub policy: DecisionPolicy,
    /// Opaque provider handle for this Decision. Echo it unchanged when
    /// answering; its spelling need not match the provider's raw wire ID.
    pub id: String,
    /// The tool call being gated — the id of its `ToolStarted`, so a Pane can
    /// put the Decision on the tool card it blocks.
    pub tool_use_id: String,
    pub tool_name: String,
    /// The provider's own one-line summary, for a Pane too small to render
    /// `input` (the wall answers Decisions without focusing).
    pub description: String,
    pub input: serde_json::Value,
    /// Provider-labelled choices. Their raw values remain opaque to the UI.
    pub suggestions: Vec<DecisionChoice>,
}

impl Decision {
    /// Async questions ask for input while execution continues. Their replies
    /// are user messages and require a transport acknowledgement.
    pub fn blocks_execution(&self) -> bool {
        self.delivery == DecisionDelivery::Blocking
    }

    /// An opaque standing choice already validated by the provider adapter.
    pub fn standing_answer(&self) -> Option<&serde_json::Value> {
        self.suggestions
            .iter()
            .find(|choice| choice.standing)
            .map(|choice| &choice.value)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn decision(suggestions: Vec<DecisionChoice>) -> Decision {
        Decision {
            delivery: Default::default(),
            kind: Default::default(),
            policy: Default::default(),
            id: "1".into(),
            tool_use_id: "toolu_1".into(),
            tool_name: "Write".into(),
            description: String::new(),
            input: serde_json::Value::Null,
            suggestions,
        }
    }

    #[test]
    fn standing_choices_are_provider_validated_and_opaque_here() {
        let offered = decision(vec![
            DecisionChoice { label: "first".into(), value: serde_json::json!({"opaque_choice": "first"}), standing: true },
            DecisionChoice { label: "second".into(), value: serde_json::json!("second"), standing: false },
        ]);
        assert_eq!(offered.standing_answer(), Some(&offered.suggestions[0].value));
        assert_eq!(decision(vec![]).standing_answer(), None);
    }
}

/// How the operator answered a `DecisionRequested`.
#[derive(Debug, Clone, PartialEq)]
pub enum DecisionAnswer {
    /// Run the tool, with this input. Normally the input the Decision arrived
    /// with, echoed back; a different value runs the tool with edits.
    Allow { input: serde_json::Value },
    /// Refuse. The message reaches the model as the tool's failed result, so
    /// the turn continues with a refusal rather than dying.
    Deny { message: String },
    /// Allow, and adopt one of the standing answers this request offered —
    /// echoed back exactly as it arrived in `Decision::suggestions`. Each
    /// provider spells the adoption its own way; both were captured answering
    /// a gated call whose repeat then ran unasked.
    AllowAlways {
        input: serde_json::Value,
        suggestion: serde_json::Value,
    },
    /// Choose one opaque, provider-offered choice.
    Choose { value: serde_json::Value },
    /// Answers a normalized question form. The provider adapter maps its
    /// stable IDs and native payload independently of the renderer.
    Questions {
        answers: Vec<crate::questions::Answer>,
    },
    /// Values for a normalized MCP form.
    Form { values: serde_json::Value },
    /// Cancel an elicitation without treating it as a tool denial.
    Cancel,
}

/// How a turn ended.
#[derive(Debug, Clone, PartialEq)]
pub enum TurnOutcome {
    Completed,
    Interrupted,
    Error(String),
}
